//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.26 at 03:13:57 PM EAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.oorsprong.org/websamples.countryinfo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.oorsprong.websamples;
